### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by derhansen** [qbus-agentur/nginx_cache#11]
Since TYPO3 v10 is about to be released soon, I would like to know your plans for this extension. 
Will there be a v10 compatible version? Do you want to drop support for unsupported TYPO3 versions (e.g. 7.6 and 8.7). Any refactorings, you would like to do? I can help with code and testing if wanted.

**Comment by bnf** [comment]
I will definitely add support for TYPO3 v10 and prepared some code already. Functional tests do already pass, but I performed only very basic manual tests so far.
You may check out the https://github.com/qbus-agentur/nginx_cache/tree/typo3-v10 branch if you would like to test upfront.

**Comment by bnf** [comment]
> Do you want to drop support for unsupported TYPO3 versions (e.g. 7.6 and 8.7). Any refactorings, you would like to do?

Not in the next release. It will only add support for TYPO3 v10.

I then plan to drop 7.6 (and probably 8.7) and PHP <7.2 in a new feature release to add the [purger-interface](https://github.com/qbus-agentur/nginx_cache/tree/purger-interface) branch with proper PHP 7.2 type declarations.

I think we should also try to make use of the TYPO3 v9 site config for better cli-based cache flushing, but there are no real plans/tests yet.
